import { z } from 'zod'

// ─── Primitives ───────────────────────────────────────────────────────────────

export const MigrationStatusSchema = z.enum(['applied', 'pending', 'failed'])
export const RiskLevelSchema = z.enum(['low', 'medium', 'high', 'critical'])
export const DriftTypeSchema = z.enum([
  'table-missing',
  'table-extra',
  'column-mismatch',
  'index-change',
  'constraint-change',
  'unknown',
  'missing_migration',
  'extra_column',
  'extra_table',
  'modified_migration',
])
export const DriftDetectionStatusSchema = z.enum(['clean', 'drifted', 'error'])
export const LogLevelSchema = z.enum(['trace', 'debug', 'info', 'warn', 'error'])
export const WebhookTypeSchema = z.enum(['slack', 'discord', 'http'])
export const DatabaseProviderSchema = z.enum([
  'postgresql',
  'mysql',
  'sqlite',
  'sqlserver',
  'mongodb',
])
export const DriftRepairStrategySchema = z.enum(['fix-migration', 'revert-manual', 'sync-history'])
export const SchemaDiffTypeSchema = z.enum(['added', 'removed', 'modified'])

// ─── Domain objects ───────────────────────────────────────────────────────────

export const MigrationSchema = z.object({
  name: z.string().min(1),
  timestamp: z.string().datetime(),
  status: MigrationStatusSchema,
  sqlPath: z.string(),
})

export const RiskFactorSchema = z.object({
  pattern: z.string(),
  severity: RiskLevelSchema,
  description: z.string(),
  affectedTable: z.string().optional(),
  estimatedRows: z.number().int().nonnegative().optional(),
  recommendation: z.string(),
})

export const MigrationRiskScoreSchema = z.object({
  score: z.number().int().min(0).max(100),
  level: RiskLevelSchema,
  factors: z.array(RiskFactorSchema),
})

export const RollbackPlanSchema = z.object({
  migrationName: z.string(),
  sql: z.string(),
  warnings: z.array(z.string()),
  isAutoGenerated: z.boolean(),
  isFullyReversible: z.boolean(),
})

export const MigrationDetailSchema = MigrationSchema.extend({
  sql: z.string(),
  risks: z.array(z.string()),
  riskScore: MigrationRiskScoreSchema.optional(),
  rollbackPlan: RollbackPlanSchema.optional(),
  gitBranch: z.string().optional(),
})

export const DriftItemSchema = z.object({
  sql: z.string(),
  type: DriftTypeSchema,
  description: z.string(),
})

export const DriftResultSchema = z.object({
  hasDrift: z.boolean(),
  driftCount: z.number().int().nonnegative(),
  differences: z.array(DriftItemSchema),
  cachedAt: z.string().datetime().nullable(),
  status: DriftDetectionStatusSchema,
  errorMessage: z.string().optional(),
})

export const ProjectStatusSchema = z.object({
  connected: z.boolean(),
  migrationsApplied: z.number().int().nonnegative(),
  migrationsPending: z.number().int().nonnegative(),
  migrationsFailed: z.number().int().nonnegative(),
  driftDetected: z.boolean(),
  driftCount: z.number().int().nonnegative(),
  riskLevel: RiskLevelSchema,
  lastSync: z.string().datetime(),
  provider: DatabaseProviderSchema.optional(),
  projectName: z.string().optional(),
  schemaPath: z.string().optional(),
})

// ─── Simulation ───────────────────────────────────────────────────────────────

export const SimulationStatementSchema = z.object({
  sql: z.string(),
  success: z.boolean(),
  error: z.string().optional(),
  durationMs: z.number().nonnegative(),
})

export const SimulationResultSchema = z.object({
  success: z.boolean(),
  migrationName: z.string(),
  appliedStatements: z.array(SimulationStatementSchema),
  errors: z.array(z.string()),
  warnings: z.array(z.string()),
  totalDurationMs: z.number().nonnegative(),
})

// ─── Drift Recovery ───────────────────────────────────────────────────────────

export const DriftRecoverySuggestionSchema = z.object({
  driftItem: DriftItemSchema,
  strategy: DriftRepairStrategySchema,
  sql: z.string().optional(),
  description: z.string(),
  isDestructive: z.boolean(),
})

// ─── Schema Diff ──────────────────────────────────────────────────────────────

export const SchemaDiffSchema = z.object({
  type: SchemaDiffTypeSchema,
  entity: z.string(),
  field: z.string().optional(),
  before: z.string().optional(),
  after: z.string().optional(),
})

export const MigrationHistoryDiffSchema = z.object({
  name: z.string(),
  presentInSource: z.boolean(),
  presentInTarget: z.boolean(),
  statusInSource: MigrationStatusSchema.optional(),
  statusInTarget: MigrationStatusSchema.optional(),
})

export const EnvironmentComparisonSchema = z.object({
  source: z.string(),
  target: z.string(),
  schemaDiffs: z.array(SchemaDiffSchema),
  migrationDiffs: z.array(MigrationHistoryDiffSchema),
  comparedAt: z.string().datetime(),
})

// ─── Git Awareness ────────────────────────────────────────────────────────────

export const GitMigrationInfoSchema = z.object({
  migrationName: z.string(),
  branch: z.string(),
  commitHash: z.string().optional(),
  authorName: z.string().optional(),
  committedAt: z.string().optional(),
})

export const MigrationConflictSchema = z.object({
  migrationA: z.string(),
  migrationB: z.string(),
  branches: z.array(z.string()),
  conflictType: z.enum(['timestamp-overlap', 'name-conflict', 'history-diverge']),
  description: z.string(),
})

// ─── Pagination query params ──────────────────────────────────────────────────

export const PaginationQuerySchema = z.object({
  page: z.coerce.number().int().positive().default(1),
  limit: z.coerce.number().int().positive().max(100).default(20),
})

// ─── Config ───────────────────────────────────────────────────────────────────

export const WebhookEventSchema = z.enum([
  'drift-detected',
  'migration-failed',
  'check-complete',
  'migration-applied',
  'simulation-complete',
  'risk-threshold-exceeded',
])

export const WebhookConfigSchema = z.object({
  type: WebhookTypeSchema,
  url: z.string().url(),
  events: z.array(WebhookEventSchema).optional(),
})

export const FeatureFlagsSchema = z.object({
  riskAnalysis: z.boolean().default(true),
  webhookAlerts: z.boolean().default(false),
  auditLog: z.boolean().default(false),
  ciAnnotations: z.boolean().default(false),
  envComparison: z.boolean().default(false),
  rollbackGen: z.boolean().default(false),
  simulation: z.boolean().default(false),
  gitAwareness: z.boolean().default(false),
})

export const EnvironmentEntrySchema = z.object({
  name: z.string().min(1),
  databaseUrl: z.string().url().or(z.string().startsWith('file:')),
})

export const PrismaFlowConfigSchema = z.object({
  port: z.number().int().positive().max(65535).default(5555),
  logLevel: LogLevelSchema.default('info'),
  openBrowser: z.boolean().default(true),
  features: FeatureFlagsSchema.partial().default({}),
  webhooks: z.array(WebhookConfigSchema).default([]),
  environments: z.array(EnvironmentEntrySchema).default([]),
  auditLogMaxMb: z.number().positive().default(10),
  riskThreshold: RiskLevelSchema.default('medium'),
})

export type PrismaFlowConfigParsed = z.infer<typeof PrismaFlowConfigSchema>

// ─── SaaS Schemas ─────────────────────────────────────────────────────────────

export const OrganizationSchema = z.object({
  id: z.string().uuid(),
  name: z.string().min(1),
  slug: z
    .string()
    .min(1)
    .regex(/^[a-z0-9-]+$/),
  createdAt: z.string().datetime(),
})

export const TeamSchema = z.object({
  id: z.string().uuid(),
  name: z.string().min(1),
  organizationId: z.string().uuid(),
  createdAt: z.string().datetime(),
})

export const ProjectSchema = z.object({
  id: z.string().uuid(),
  name: z.string().min(1),
  organizationId: z.string().uuid(),
  teamId: z.string().uuid().optional(),
  createdAt: z.string().datetime(),
  updatedAt: z.string().datetime(),
})

export const EnvironmentSchema = z.object({
  id: z.string().uuid(),
  name: z.string().min(1),
  projectId: z.string().uuid(),
  provider: DatabaseProviderSchema,
  connectionString: z.string().optional(),
  createdAt: z.string().datetime(),
  updatedAt: z.string().datetime(),
})

export const DeploymentEventSchema = z.object({
  id: z.string().uuid(),
  projectId: z.string().uuid(),
  environmentId: z.string().uuid(),
  migrationsApplied: z.array(z.string()),
  appliedBy: z.string().optional(),
  durationMs: z.number().nonnegative(),
  success: z.boolean(),
  error: z.string().optional(),
  createdAt: z.string().datetime(),
})
